[package]
name = "wave-engine"
version = "0.1.1"
edition = "2021"

[dependencies]
num = "0.4.0"
rand = "0.8.5"
gl = "0.14.0"
ash = {version = "0.37.3+1.3.251", features = ["linked"]}
chrono = "0.4.26"
glfw = {version = "0.54.0", features = ["vulkan"]}
once_cell = "1.18.0"

[features]
debug = []
profiler = []

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"
