[package]
name = "wave-engine"
version = "0.1.1"
edition = "2021"

[dependencies]
num = "0.4.0"
rand = "0.8.5"
gl = {version = "0.14.0"}
chrono = "0.4.26"
imgui-glfw-rs = "0.4.1"
once_cell = "1.18.0"

[features]
trace = []
logging = []

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"
