[package]
name = "wave-engine"
version = "0.1.2"
edition = "2021"

[dependencies]
num = "0.4.1"
rand = "0.8.5"
gl46 = "0.2.1"
gl = { version = "0.14.0", features = [] }
ash = {version = "0.37.3", features = ["linked"]}
chrono = "0.4.31"
glfw = {version = "0.54.0", features = ["vulkan"]}
once_cell = "1.19.0"
shaderc = "0.8.3"

[features]
default = []
debug = []
profiler = []
Vulkan = []

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"
