name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: sudo apt install libxi-dev;
        sudo apt install libxcursor-dev;
        sudo apt install libxinerama-dev;
        sudo apt install libxrandr-dev;
        sudo apt install libglfw3-dev;
        cargo build +stable build --color=always --message-format=json-diagnostic-rendered-ansi --package wave-engine --all-features;
        cargo test -- --test-threads=1 --show-output;
